In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
file_path="C:\\Users\\user\\Downloads\\datasets\\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df.head(5)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [4]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
pd.DataFrame(d1)

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

In [18]:
d1={"Name":["ram","sita","laxman",None],  #None is not recommed np.none is used
    x 
   "Age":[31,32,None,33],
    "City":[None,"hyd","Pune","Chennai"]
   }
pd.DataFrame(d1)

     Name   Age     City
0     ram  31.0     None
1    sita  32.0      hyd
2  laxman   NaN     Pune
3    None  33.0  Chennai

In [9]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

**Method - 1**
- fill with a random number to all NULL values

In [10]:
df.isnull()

    Name    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [11]:
df.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

**fillna**
- filling random value

In [16]:
df.fillna(40,inplace=True)
df

     Name   Age     City
0     ram  31.0       40
1    sita  32.0      hyd
2  laxman  40.0     Pune
3      40  33.0  Chennai

In [17]:
df.dtypes

Name     object
Age     float64
City     object
dtype: object

**Method- 2**
- fill the random value by using column wise by fillna

In [24]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

In [ ]:
df["Name"].fillna("Raheem",inplace=True)

In [ ]:
df["Age"].fillna(40,inplace=True)

In [ ]:
df["City"].fillna("new york",inplace=True)

In [28]:
df

     Name   Age      City
0     ram  31.0  new york
1    sita  32.0       hyd
2  laxman  40.0      Pune
3  Raheem  33.0   Chennai

**Method- 3**
- methods used to fill missing values
- pad

- bfill

- backfill

- ffill

In [31]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

**method=pad**
- every NAN value is filled with its above value (copied aboved value)

In [33]:
df.fillna(method="pad")

C:\Users\user\AppData\Local\Temp\ipykernel_3424\4167762737.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="pad")

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman  32.0     Pune
3  laxman  33.0  Chennai

**method=bfill**
- in this NAN values is replaced with the below value

In [35]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

In [36]:
df.fillna(method="bfill")

C:\Users\user\AppData\Local\Temp\ipykernel_3424\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

     Name   Age     City
0     ram  31.0      hyd
1    sita  32.0      hyd
2  laxman  33.0     Pune
3     NaN  33.0  Chennai

**method backfill**
- same as bfill

In [37]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

In [38]:
df.fillna(method="backfill")

C:\Users\user\AppData\Local\Temp\ipykernel_3424\28332659.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="backfill")

     Name   Age     City
0     ram  31.0      hyd
1    sita  32.0      hyd
2  laxman  33.0     Pune
3     NaN  33.0  Chennai

**method=ffill**
- same as pad

In [39]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

In [45]:
df.fillna(method="ffill",axis=1) #wrng o/p

C:\Users\user\AppData\Local\Temp\ipykernel_3424\2641629133.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill",axis=1) #wrng o/p

     Name     Age     City
0     ram    31.0     31.0
1    sita    32.0      hyd
2  laxman  laxman     Pune
3     NaN    33.0  Chennai

|**Method -4**
- mean,median,mode
- mean,median is used for numerical datta
- mode is used for categorical data

In [44]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

**mean**
- instead of providing the direct random value to missing value fill that value with mean of that column
- same as median and mode

In [52]:
df["Age"].fillna(df["Age"].mean(),inplace=True) #mean is 32

In [53]:
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman  32.0     Pune
3     NaN  33.0  Chennai

In [54]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

In [56]:
df["Age"].fillna(df["Age"].median(),inplace=True)
df

C:\Users\user\AppData\Local\Temp\ipykernel_3424\1557397881.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman  32.0     Pune
3     NaN  33.0  Chennai

In [57]:
d1={"Name":["ram","sita","laxman",np.nan],
   "Age":[31,32,np.nan,33],
    "City":[np.nan,"hyd","Pune","Chennai"]
   }
df=pd.DataFrame(d1)
df

     Name   Age     City
0     ram  31.0      NaN
1    sita  32.0      hyd
2  laxman   NaN     Pune
3     NaN  33.0  Chennai

In [61]:
df["Name"].fillna(method="pad",inplac)

C:\Users\user\AppData\Local\Temp\ipykernel_3424\2045731578.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Name"].fillna(method="ffill")

0       ram
1      sita
2    laxman
3    laxman
Name: Name, dtype: object