In [1]:
import numpy as np
import pandas as pd

In [6]:
visa_df=pd.read_csv(r"C:\Users\user\Downloads\datasets\Visadataset.csv")
visa_df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

**One Hot Encoder:**
- one hot encoder means at a time one is on(1/True) other is off(0/False)

|case_Status|certified|denied|
|-----------|---------|------|
|certified  |   1     | 0    |
|Denied     |   0     | 1    |

**advantages**
- one hot encoder new columns are orthogonal each other

- orthogonally means 90 degree phase shift

- 90 degree means perpendicular means independent to each other

- independent means no relation

- it is very important property

**Disadvantages:**
- assume that u have 100 unique labels for a column

- so it will create 100 new columns

- to process 100 columns we require more memory,more time and more hardware

- this is called curse of dimensionality

**pd.get_dummies()**

In [7]:
visa_df=pd.read_csv(r"C:\Users\user\Downloads\datasets\Visadataset.csv")
visa_df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

- pd.get_dummies(visa_df,columns=[]) it returns the ans in true or false to want ans in interger like 0,1
- use pd.get_dummies(visa_df,columns=[],dtypes=int)

In [14]:
pd.get_dummies(visa_df,columns=["case_status"]).head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status_Certified,case_status_Denied
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,False,True
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,True,False
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,False,True
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,False,True
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,True,False

In [16]:
pd.get_dummies(visa_df,columns=["case_status"],dtype=int).head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status_Certified,case_status_Denied
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,0,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,1,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,0,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,0,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,1,0