**Step 1: import  packages**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**step 2: read data**  visa dataset
- to read a file required:
- file location,file name and extension

In [6]:
file_path="C:\\Users\\user\\Downloads\\archive\\bank.csv"
pd.read_csv(file_path,sep=';')              
#use sep=";" as ; is separator all in one column

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

**step 3: create a data frame using list**

In [11]:
l1=["ram","raheem","robert"]
l2=[30,31,32]
col=["name","age"]
names=pd.DataFrame(zip(l1,l2),columns=col,)

In [12]:
names

     name  age
0     ram   30
1  raheem   31
2  robert   32

**step 4 how to save dataframe in local pc**
- what is your file name===name
- where to save location
- what file name u want to provide====NAMES

In [13]:
names.to_csv("C:\\Users\\user\\Downloads\\archive\\NAMES.csv")

In [16]:
names.to_csv("NAMES.csv") #stores where the current  python file is stored eg eda location

In [20]:
names.to_csv("NAMES1.csv",index=False)  # stores without index

In [32]:
file_path="C:\\Users\\user\\Downloads\\archive\\NAMES.csv"
pd.read_csv(file_path)

   Unnamed: 0    name  age
0           0     ram   30
1           1  raheem   31
2           2  robert   32

In [28]:
file_path="NAMES1.csv"
pd.read_csv(file_path)

     name  age
0     ram   30
1  raheem   31
2  robert   32

In [30]:
l3=["eng","maths","sci"]
l4=[99,87,85]
pd.DataFrame(zip(l3,l4),columns=["sub","marks"])

     sub  marks
0    eng     99
1  maths     87
2    sci     85

**step 5: Add a new column to exitising dataframe**

- what is dataframe name ===>names
- what is name of the column u want to add===>cities
- how many rows in original data-===>3
- what is new data==['hyd','ban','mun'] if 3 rows 3 new data should add

In [37]:
names['city']=["hyd","bang","delhi"] # if 4 values are added error occured

In [36]:
names

     name  age   city
0     ram   30    hyd
1  raheem   31   bang
2  robert   32  delhi

**step 6: how to drop/delete the column**

- what is your dataframe name
- axis=1 =====> columns
- axis=0 =====> rows
- what is name of the columns===>city
- when u drop the column you are modify the table
- then dataframe should be overwrite  ====>inplace means data will overwrite
-  or you want to create a new dataset

In [ ]:
names.drop('city',inplace=True,axis=1)   #axis=1 indicates columns 
                                         #inplace=True overwrites

In [42]:
names

     name  age
0     ram   30
1  raheem   31
2  robert   32

**Creating DataFrames using Dict{}**

In [2]:
dic1={"Name":["ram","raheem","robert"],
     "Age":[30,31,32]}
dic1

{'Name': ['ram', 'raheem', 'robert'], 'Age': [30, 31, 32]}

In [12]:
names=pd.DataFrame(dic1,index=[1,2,3])
# no need to provide columns names
names['id']=[1,2,3]
names

     Name  Age  id
1     ram   30   1
2  raheem   31   2
3  robert   32   3